Song.create(name:"Youuu", artist:"COIN", genre: "Alt Rock")
Song.create(name:"Breezeblocks", artist:"alt-J", genre: "Alt Rock")
Song.create(name:"Baguetti", artist:"Smino", genre: "Rap")
Song.create(name:"La Di Da", artist:"Lennon Stella", genre: "Pop")
Song.create(name:"Mob Ties", artist:"Drake", genre: "Rap")
Song.create(name:"The Bees Knees", artist:"Juice WRLD", genre: "Rap")
Song.create(name:"Scar Tissue", artist:"Red Hot Chili Peppers", genre: "Rock")
Song.create(name:"Banana Pancakes", artist:"Jack Johnson", genre: "Chill Acoustic")
Song.create(name:"Riptide", artist:"Vance Joy", genre: "Pop Rock")